const SUPABASE_URL="https://lhxgfstmzdbpkmyytbse.supabase.co";
const SUPABASE_KEY="sb_publishable_HZiFjnZZAsHyECLha2LM9g_cBB3WDUe";
const RECOVERY=location.hash.includes("type=recovery")||location.search.includes("type=recovery");
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.getElementById("app");
let S={user:null,profile:null,jobs:[],job:null,tab:"home",msg:"",err:"",mode:"signin",f:{name:"",email:"",pass:"",role:"worker"}};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=x=>"$"+Number(x||0).toFixed(2);
const date=x=>x?new Date(x).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"—";
const mins=(a,b=new Date())=>Math.max(0,Math.floor((new Date(b)-new Date(a))/60000));
const dur=(a,b)=>{let m=mins(a,b);return `${Math.floor(m/60)}h ${m%60}m`};
function theme(){let t=localStorage.tcTheme||"system";document.documentElement.dataset.theme=t==="system"?(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"):t}
function friendly(m){m=String(m||"");let l=m.toLowerCase();
if(l.includes("invalid login"))return "Wrong email or password. No account yet? Tap 'Create an account' below.";
if(l.includes("not confirmed"))return "Please confirm your email first. Check your inbox for the confirmation link.";
if(l.includes("already registered"))return "An account with this email already exists. Tap 'Sign in' instead, or use Forgot Password.";
if(l.includes("rate limit")||l.includes("too many")||l.includes("security purposes")||l.includes("429"))return "Too many tries. Wait a minute and try again.";
if(l.includes("password")&&l.includes("character"))return "Password is too short. Use at least 6 characters.";
if(l.includes("valid email")||l.includes("invalid email"))return "That doesn't look like a valid email.";
if(l.includes("failed to fetch")||l.includes("network"))return "Can't connect. Check your internet and try again.";
return m}
function toast(x,e=false){S.msg=e?"":x;S.err=e?x:"";render();setTimeout(()=>{S.msg=S.err="";document.querySelectorAll(".notice,.error").forEach(e=>e.remove())},6000)}
async function load(){
 const {data:{user}}=await db.auth.getUser();S.user=user;
 if(!user){S.profile=null;S.need2fa=false;return}
 if(await needMfa()){S.need2fa=true;S.profile=null;return}S.need2fa=false;
 const p=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();
 S.profile=p.data;
 if(!S.profile&&user.user_metadata?.name){let ins=await db.from("profiles").insert({id:user.id,name:user.user_metadata.name,role:user.user_metadata.role||"worker"}).select().single();S.profile=ins.data||null}
 if(S.profile?.role==="manager"){let r=await db.from("jobs").select("*").eq("owner_id",user.id).order("created_at",{ascending:false});S.jobs=r.data||[]}
 else {let r=await db.from("job_workers").select("job_id,status,jobs(*)").eq("worker_id",user.id);S.jobs=(r.data||[]).filter(x=>x.status==="active"&&x.jobs).map(x=>x.jobs)}
}
async function boot(){theme();await load();render();if(RECOVERY)newPass();db.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY")setTimeout(newPass,0);setTimeout(async()=>{await load();render()},0)})}
boot();

function banner(){return `${S.msg?`<div class="notice">${esc(S.msg)}</div>`:""}${S.err?`<div class="error">${esc(S.err)}</div>`:""}`}
function auth(){
const f=S.f,up=S.mode==="signup";
const eye=`<button type="button" onclick="togglePw(this)" style="position:absolute;right:6px;top:50%;transform:translateY(-50%);background:transparent;border:0;box-shadow:none;padding:6px 10px;width:auto;min-width:0;cursor:pointer;font-size:18px">👁️</button>`;
return `<div class="auth"><div class="hero"><div class="logo">⏱️</div><h1>TimeClock</h1><p>Track shifts, tasks, requests, and jobs.</p></div>
<div class="card"><h2>${up?"Create Account":"Sign In"}</h2>${banner()}
${up?`<label>Your name</label><input id="name" type="text" placeholder="Name TimeClock will show" value="${esc(f.name)}" oninput="S.f.name=this.value">`:""}
<label>Email</label><input id="email" type="email" value="${esc(f.email)}" oninput="S.f.email=this.value">
<label>Password</label><div style="position:relative"><input id="pass" type="password" style="padding-right:48px" value="${esc(f.pass)}" oninput="S.f.pass=this.value">${eye}</div>
${up?`<label>Account type</label><select id="role" onchange="S.f.role=this.value"><option value="worker" ${f.role==="worker"?"selected":""}>👷 Worker</option><option value="manager" ${f.role==="manager"?"selected":""}>👑 Manager / Employer</option></select>`:""}
<div class="actions">${up?`<button class="primary" onclick="signup()">Create Account</button>`:`<button class="primary" onclick="login()">Sign In</button><button class="secondary" onclick="resetPassword()">Forgot Password?</button>`}</div>
<p class="small">${up?`Already have an account? <a href="#" onclick="setMode('signin');return false">Sign in</a>`:`New here? <a href="#" onclick="setMode('signup');return false">Create an account</a>`}</p>
<p class="small">Supabase securely handles your password. · v8</p></div></div>`}
function setup(){return `<div class="auth"><div class="hero"><div class="logo">⏱️</div><h1>Finish Setup</h1><p>You're signed in, but your profile isn't set up yet.</p></div>
<div class="card"><h2>Your profile</h2>${banner()}<label>Your name</label><input id="sname" type="text" placeholder="Name TimeClock will show" value="${esc(S.f.name)}" oninput="S.f.name=this.value">
<label>Account type</label><select id="srole" onchange="S.f.role=this.value"><option value="worker" ${S.f.role==="worker"?"selected":""}>👷 Worker</option><option value="manager" ${S.f.role==="manager"?"selected":""}>👑 Manager / Employer</option></select>
<div class="actions"><button class="primary" onclick="saveProfile()">Save and Continue</button><button class="secondary" onclick="logout()">Sign Out</button></div></div></div>`}
async function saveProfile(){let name=(S.f.name||"").trim();if(!name)return toast("Enter your name.",true);let p=await db.from("profiles").insert({id:S.user.id,name,role:S.f.role}).select().single();if(p.error)return toast(friendly(p.error.message),true);S.profile=p.data;await load();render()}
function wrap(c){
return `<div class="app"><div class="row"><div><b>⏱️ TimeClock</b><div class="small">${esc(S.profile?.name)} · ${S.profile?.role}</div></div>
<div class="actions"><button class="secondary" onclick="cycleTheme()">🌙 Theme</button><button class="secondary" onclick="mfaDialog()">🔐 2FA</button><button class="secondary" onclick="logout()">Sign Out</button></div></div>
${S.msg?`<div class="notice">${esc(S.msg)}</div>`:""}${S.err?`<div class="error">${esc(S.err)}</div>`:""}${c}</div>`}
function render(){theme();if(!S.user||!S.profile){app.innerHTML=S.need2fa?codeScreen():S.user?setup():auth();return}app.innerHTML=wrap(S.profile.role==="manager"?manager():worker())}
async function login(){let email=emailEl().value.trim(),pass=passEl().value;if(!email||!pass)return toast("Enter email and password.",true);let r=await db.auth.signInWithPassword({email,password:pass});if(r.error)return toast(friendly(r.error.message),true);toast("Signed in.")}
async function signup(){let name=f_name(),email=emailEl().value.trim(),pass=passEl().value,role=S.f.role;if(!name)return toast("Enter your name.",true);if(!email||pass.length<6)return toast("Use an email and a password of at least 6 characters.",true);let r=await db.auth.signUp({email,password:pass,options:{data:{name,role}}});if(r.error)return toast(friendly(r.error.message),true);if(r.data.user&&r.data.user.identities&&r.data.user.identities.length===0)return toast(friendly("already registered"),true);if(!r.data.session)return toast("Check your email to confirm, then sign in.");let p=await db.from("profiles").insert({id:r.data.user.id,name,role}).select().single();if(p.error)return toast(p.error.message,true);S.profile=p.data;render()}
const emailEl=()=>document.getElementById("email"),passEl=()=>document.getElementById("pass");
async function resetPassword(){let email=emailEl().value.trim();if(!email)return toast("Type your email first, then tap Forgot Password.",true);let r=await db.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+window.location.pathname});if(r.error)return toast(friendly(r.error.message),true);toast("Check your email for the reset link.")}
const f_name=()=>(document.getElementById("name")?.value||"").trim();
function setMode(m){S.mode=m;render()}
function togglePw(b){let i=b.previousElementSibling,show=i.type==="password";i.type=show?"text":"password";b.textContent=show?"🙈":"👁️"}
let npOpen=false;function newPass(){if(npOpen)return;npOpen=true;let d=document.createElement("dialog");d.innerHTML=`<h2>Set New Password</h2><label>New password</label><input id="np" type="password" placeholder="6+ characters"><div class="actions"><button class="primary" id="npb">Save Password</button></div>`;document.body.append(d);d.showModal();d.querySelector("#npb").onclick=async()=>{let p=d.querySelector("#np").value;if(p.length<6)return alert("Use at least 6 characters.");let r=await db.auth.updateUser({password:p});if(r.error)return alert(r.error.message);d.close();d.remove();npOpen=false;history.replaceState(null,"",location.pathname);toast("Password updated.")}}
async function logout(){await db.auth.signOut();S={user:null,profile:null,jobs:[],job:null,tab:"home",msg:"",err:"",mode:"signin",f:{name:"",email:"",pass:"",role:"worker"}};render()}
function cycleTheme(){let t=localStorage.tcTheme||"system";localStorage.tcTheme=t==="system"?"dark":t==="dark"?"light":"system";theme();render()}
function chooseJob(id){S.job=S.jobs.find(x=>x.id===id);S.tab="home";render();if(S.profile.role==="manager")loadManagerHome()}
function manager(){
if(!S.job)return wrapInner(`<div class="hero"><h1>👑 Manager</h1><p>Choose a job or create one.</p></div>
<div class="grid">${S.jobs.map(j=>`<div class="card"><h2>${esc(j.name)}</h2><p>${esc(j.description||"")}</p><span class="badge">${j.visibility==="public"?"🌎 Public":"🔒 Private"}</span><div class="actions"><button class="primary" onclick="chooseJob('${j.id}')">Open</button></div></div>`).join("")||`<div class="card empty">No jobs yet.</div>`}</div>
<div class="card"><h2>Create Job</h2><label>Name</label><input id="jn" placeholder="Example: JB's Landscaping"><label>Description</label><textarea id="jd"></textarea><label>Visibility</label><select id="jv"><option value="private">🔒 Private</option><option value="public">🌎 Public</option></select><label>Location / area</label><input id="jl" placeholder="Optional"><div class="actions"><button class="primary" onclick="createJob()">Create Job</button></div></div>`);
let nav=["home","workers","requests","tasks","schedule","payroll","settings"],labels=["🏠 Home","👥 Workers","📋 Requests","💰 Tasks","🗓️ Schedule","💵 Payroll","⚙️ Settings"];
return wrapInner(`<div class="tabs">${nav.map((x,i)=>`<button class="${S.tab===x?"primary":"secondary"}" onclick="S.tab='${x}';render()">${labels[i]}</button>`).join("")}</div>
${S.tab==="home"?mhome():S.tab==="workers"?mworkers():S.tab==="requests"?mrequests():S.tab==="tasks"?mtasks():S.tab==="schedule"?mschedule():S.tab==="payroll"?mpayroll():msettings()}`)}
function wrapInner(x){return x}
function mhome(){return `<div class="row"><div><h1>${esc(S.job.name)}</h1><p>${esc(S.job.description||"")}</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div>
<div class="grid"><div class="stat">👥<b id="wc">...</b>Workers</div><div class="stat">🟢<b id="ww">...</b>Working</div><div class="stat">📋<b id="rq">...</b>Requests</div></div>
<div class="card"><h2>Who's Working?</h2><div id="who">Loading...</div></div>`}
async function loadManagerHome(){let j=S.job;let m=await db.from("job_workers").select("worker_id,status").eq("job_id",j.id);let ids=(m.data||[]).filter(x=>x.status==="active").map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let o=ids.length?await db.from("time_records").select("worker_id,clock_in").eq("job_id",j.id).is("clock_out",null):{data:[]};let q=await db.from("time_change_requests").select("*",{count:"exact",head:true}).eq("job_id",j.id).eq("status","pending");document.getElementById("wc").textContent=ids.length;document.getElementById("ww").textContent=(o.data||[]).length;document.getElementById("rq").textContent=q.count||0;let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("who").innerHTML=(m.data||[]).filter(x=>x.status==="active").map(x=>{let r=(o.data||[]).find(y=>y.worker_id===x.worker_id);return `<div class="item row"><div><b>${esc(map.get(x.worker_id)||"Worker")}</b><div class="small">${r?"Started "+date(r.clock_in):"Not working"}</div></div><span class="status ${r?"working":""}">${r?dur(r.clock_in):"Not Working"}</span></div>`}).join("")||`<div class="empty">No workers yet.</div>`}
function mworkers(){return `<div class="row"><div><h1>Workers</h1><p>Current and former workers.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div>
<div class="card"><h2>Join Code</h2><div class="code">${esc(S.job.join_code||"")}</div><div class="actions"><button class="secondary" onclick="navigator.clipboard.writeText('${esc(S.job.join_code)}');toast('Copied')">Copy</button><button class="secondary" onclick="regen()">Regenerate</button></div></div>
<div class="card"><h2>Workers</h2><div id="wl">Loading...</div></div>`}
async function loadWorkers(){let m=await db.from("job_workers").select("*").eq("job_id",S.job.id).order("joined_at",{ascending:false});let ids=(m.data||[]).map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("wl").innerHTML=(m.data||[]).map(x=>`<div class="item row"><div><b>${esc(map.get(x.worker_id)||"Worker")}</b><div class="small">${x.status}</div></div>${x.status==="active"?`<button class="danger" onclick="removeWorker('${x.id}')">Remove</button>`:`<button class="success" onclick="restore('${x.id}')">Restore</button>`}</div>`).join("")||`<div class="empty">No workers.</div>`}
function mrequests(){return `<div class="row"><div><h1>Requests</h1><p>Review custom times and public-job join requests.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><h2>Time Requests</h2><div id="trs">Loading...</div></div><div class="card"><h2>Join Requests</h2><div id="jrs">Loading...</div></div>`}
async function loadRequests(){let r=await db.from("time_change_requests").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});let ids=[...new Set((r.data||[]).map(x=>x.worker_id))];let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("trs").innerHTML=(r.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(map.get(x.worker_id)||"Worker")}</b><span class="badge">${x.status}</span></div><p>${x.request_type} → ${date(x.requested_time)}<br>${esc(x.reason||"No description provided.")}</p>${x.status==="pending"?`<div class="actions"><button class="success" onclick="reviewTime('${x.id}','approved')">Approve</button><button class="danger" onclick="reviewTime('${x.id}','denied')">Deny</button></div>`:""}</div>`).join("")||`<div class="empty">No requests.</div>`;
let jr=await db.from("job_join_requests").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});let ids2=[...new Set((jr.data||[]).map(x=>x.worker_id))];let p2=ids2.length?await db.from("profiles").select("id,name").in("id",ids2):{data:[]};let map2=new Map((p2.data||[]).map(x=>[x.id,x.name]));document.getElementById("jrs").innerHTML=(jr.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(map2.get(x.worker_id)||"Worker")}</b><span class="badge">${x.status}</span></div><p>${esc(x.message||"No message.")}</p>${x.status==="pending"?`<div class="actions"><button class="success" onclick="reviewJoin('${x.id}','approved','${x.worker_id}')">Approve</button><button class="danger" onclick="reviewJoin('${x.id}','denied')">Deny</button></div>`:""}</div>`).join("")||`<div class="empty">No join requests.</div>`}
function mtasks(){return `<div class="row"><div><h1>💰 Paid Tasks</h1><p>Assign extra paid work.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><h2>New Task</h2><label>Title</label><input id="tt"><label>Description</label><textarea id="td"></textarea><label>Pay</label><input id="tp" type="number" min="0" step=".01"><label>Worker</label><select id="tw"><option value="">Choose worker</option></select><div class="actions"><button class="primary" onclick="createTask()">Assign Task</button></div></div><div class="card"><h2>Tasks</h2><div id="tl">Loading...</div></div>`}
async function loadTasks(){let m=await db.from("job_workers").select("worker_id").eq("job_id",S.job.id).eq("status","active");let ids=(m.data||[]).map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("tw").innerHTML=`<option value="">Choose worker</option>`+(p.data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");let t=await db.from("tasks").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});document.getElementById("tl").innerHTML=(t.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(x.title)}</b><span class="badge">${x.status}</span></div><p>${esc(x.description||"")}<br>${money(x.pay_amount)} · ${esc(map.get(x.assigned_worker_id)||"Unassigned")}</p>${x.status==="completed"?`<button class="success" onclick="approveTask('${x.id}')">Approve</button>`:""}</div>`).join("")||`<div class="empty">No tasks.</div>`}
function msettings(){return `<div class="row"><div><h1>Settings</h1></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><label>Job name</label><input id="en" value="${esc(S.job.name)}"><label>Description</label><textarea id="ed">${esc(S.job.description||"")}</textarea><label>Visibility</label><select id="ev"><option value="private" ${S.job.visibility==="private"?"selected":""}>🔒 Private</option><option value="public" ${S.job.visibility==="public"?"selected":""}>🌎 Public</option></select><button class="primary" onclick="saveJob()">Save</button></div>`}
function worker(){if(!S.job)return wrapInner(`<div class="hero"><h1>👷 Welcome, ${esc(S.profile.name)}</h1><p>Open a job or browse public jobs.</p></div><div class="card"><h2>My Jobs</h2><div class="grid">${S.jobs.map(j=>`<div class="card"><h3>${esc(j.name)}</h3><p>${esc(j.description||"")}</p><button class="primary" onclick="chooseJob('${j.id}')">Open</button></div>`).join("")||`<div class="empty">No jobs yet.</div>`}</div></div><div class="card"><h2>🔎 Browse Jobs</h2><button class="primary" onclick="browse()">Browse Public Jobs</button></div><div class="card"><h2>🔑 Private Job</h2><input id="code" placeholder="Job code"><button class="secondary" onclick="joinCode()">Join with Code</button></div>`);
let nav=["home","schedule","history","tasks","pay","settings"],lab=["🏠 Home","🗓️ Schedule","📅 History","💰 Tasks","💵 Pay","⚙️ Settings"];return wrapInner(`<div class="tabs">${nav.map((x,i)=>`<button class="${S.tab===x?"primary":"secondary"}" onclick="S.tab='${x}';render()">${lab[i]}</button>`).join("")}</div>${S.tab==="home"?whome():S.tab==="schedule"?wschedule():S.tab==="history"?whistory():S.tab==="tasks"?wtasks():S.tab==="pay"?wpay():wsettings()}`)}
function whome(){return `<div class="row"><div><h1>${esc(S.job.name)}</h1><p>${esc(S.job.description||"")}</p></div><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card" id="clockCard">Loading...</div>`}
async function loadWorkerHome(){let r=await db.from("time_records").select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id).is("clock_out",null).limit(1);let x=r.data?.[0];document.getElementById("clockCard").innerHTML=`<div style="text-align:center"><span class="status ${x?"working":""}">${x?"🟢 Working":"⚪ Not Working"}</span><h2>${x?dur(x.clock_in):"Ready to work"}</h2><p>${x?"Clocked in "+date(x.clock_in):"Clock in now or request a custom time."}</p><div class="actions" style="justify-content:center">${x?`<button class="danger big" onclick="clockOut('${x.id}')">⏹ Clock Out Now</button><button class="secondary big" onclick="custom('clock_out','${x.id}')">🕐 Request Custom Clock Out</button>`:`<button class="success big" onclick="clockIn()">▶ Clock In Now</button><button class="secondary big" onclick="custom('clock_in','')">🕐 Request Custom Clock In</button>`}</div></div>`}
async function whistoryData(){let r=await db.from("time_records").select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id).order("clock_in",{ascending:false}).limit(50);return `<div class="row"><h1>History</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card">${(r.data||[]).map(x=>`<div class="item row"><div><b>${date(x.clock_in)}</b><div class="small">${x.clock_out?dur(x.clock_in,x.clock_out):"Still working"}${x.manager_edited?" · Manager approved edit":""}</div></div></div>`).join("")||`<div class="empty">No shifts.</div>`}</div>`}
async function wtasksData(){let t=await db.from("tasks").select("*").eq("job_id",S.job.id).eq("assigned_worker_id",S.user.id).order("created_at",{ascending:false});return `<div class="row"><h1>💰 Tasks</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card">${(t.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(x.title)}</b><span class="badge">${x.status}</span></div><p>${esc(x.description||"")}<br><b>${money(x.pay_amount)}</b></p>${x.status==="assigned"?`<button class="primary" onclick="completeTask('${x.id}')">Mark Complete</button>`:""}</div>`).join("")||`<div class="empty">No tasks.</div>`}</div>`}
function wsettings(){return `<div class="card"><h1>Settings</h1><select onchange="localStorage.tcTheme=this.value;theme();render()"><option>system</option><option>light</option><option>dark</option></select></div>`}
async function createJob(){let n=document.getElementById("jn").value.trim();if(!n)return toast("Enter a job name.",true);let r=await db.from("jobs").insert({owner_id:S.user.id,name:n,description:document.getElementById("jd").value.trim()||null,visibility:document.getElementById("jv").value,location_text:document.getElementById("jl").value.trim()||null,join_code:codegen()}).select().single();if(r.error)return toast(r.error.message,true);S.jobs.unshift(r.data);S.job=r.data;render()}
function codegen(){let a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",s="";for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];return s.slice(0,3)+"-"+s.slice(3)}
async function regen(){let r=await db.from("jobs").update({join_code:codegen()}).eq("id",S.job.id).select().single();if(r.error)return toast(r.error.message,true);S.job=r.data;S.jobs=S.jobs.map(j=>j.id===r.data.id?r.data:j);render();toast("New join code created.")}
async function removeWorker(id){if(!confirm("Remove this worker? Their history stays."))return;let r=await db.from("job_workers").update({status:"inactive",left_at:new Date().toISOString()}).eq("id",id);if(r.error)return toast(r.error.message,true);render()}
async function restore(id){let r=await db.from("job_workers").update({status:"active",left_at:null}).eq("id",id);if(r.error)return toast(r.error.message,true);render()}
async function reviewJoin(id,status,wid){let r=await db.from("job_join_requests").update({status,reviewed_by:S.user.id,reviewed_at:new Date().toISOString()}).eq("id",id).select().single();if(r.error)return toast(r.error.message,true);if(status==="approved"){let x=await db.from("job_workers").upsert({job_id:S.job.id,worker_id:wid,status:"active"},{onConflict:"job_id,worker_id"});if(x.error)return toast(x.error.message,true)}render();toast(status==="approved"?"Worker approved.":"Denied.")}
async function reviewTime(id,status){let r=await db.from("time_change_requests").update({status,reviewed_by:S.user.id,reviewed_at:new Date().toISOString()}).eq("id",id).select().single();if(r.error)return toast(r.error.message,true);if(status==="approved"){let x=r.data;if(x.time_record_id){let field=x.request_type==="clock_in"?"clock_in":"clock_out";let u=await db.from("time_records").update({[field]:x.requested_time,manager_edited:true,edited_by:S.user.id,edited_at:new Date().toISOString()}).eq("id",x.time_record_id);if(u.error)return toast(u.error.message,true)}else{let u=await db.from("time_records").insert({job_id:x.job_id,worker_id:x.worker_id,clock_in:x.requested_time,notes:x.reason||null,manager_edited:true,edited_by:S.user.id,edited_at:new Date().toISOString()});if(u.error)return toast(u.error.message,true)}}render();toast(status==="approved"?"Approved.":"Denied.")}
async function clockIn(){let r=await db.from("time_records").insert({job_id:S.job.id,worker_id:S.user.id,clock_in:new Date().toISOString()});if(r.error)return toast(r.error.message,true);render();toast("Clocked in.")}
async function clockOut(id){let r=await db.from("time_records").update({clock_out:new Date().toISOString()}).eq("id",id).eq("worker_id",S.user.id).select();if(r.error)return toast(r.error.message,true);if(!r.data||!r.data.length)return toast("Couldn't clock out: the database blocked it. Run clockout-fix.sql in Supabase, then try again.",true);render();toast("Clocked out.")}
function custom(type,record){let now=new Date(),h=now.getHours()%12||12,m=String(now.getMinutes()).padStart(2,"0"),ap=now.getHours()>=12?"PM":"AM",d=document.createElement("dialog");d.innerHTML=`<h2>Request Custom ${type==="clock_in"?"Clock In":"Clock Out"}</h2><p>Your employer must approve this request.</p><div class="picker"><select id="h">${Array.from({length:12},(_,i)=>`<option ${i+1==h?"selected":""}>${i+1}</option>`).join("")}</select><select id="m">${Array.from({length:60},(_,i)=>`<option ${String(i).padStart(2,"0")==m?"selected":""}>${String(i).padStart(2,"0")}</option>`).join("")}</select><select id="a"><option ${ap==="AM"?"selected":""}>AM</option><option ${ap==="PM"?"selected":""}>PM</option></select></div><label>Optional description</label><textarea id="reason" placeholder="Why do you need this time?"></textarea><div class="actions"><button class="primary" id="send">Submit Request</button><button class="secondary" onclick="this.closest('dialog').close()">Cancel</button></div>`;document.body.append(d);d.showModal();d.querySelector("#send").onclick=async()=>{let hh=+d.querySelector("#h").value%12;if(d.querySelector("#a").value==="PM")hh+=12;let dt=new Date();dt.setHours(hh,+d.querySelector("#m").value,0,0);let r=await db.from("time_change_requests").insert({job_id:S.job.id,worker_id:S.user.id,time_record_id:record||null,request_type:type,requested_time:dt.toISOString(),reason:d.querySelector("#reason").value.trim()||null});d.close();d.remove();if(r.error)return toast(r.error.message,true);toast("Request sent to your employer.")}
}
async function browse(){let r=await db.from("jobs").select("*").eq("visibility","public").eq("active",true).order("created_at",{ascending:false});if(r.error)return toast(r.error.message,true);let d=document.createElement("dialog");d.innerHTML=`<h2>🌎 Browse Jobs</h2>${(r.data||[]).map(j=>`<div class="item"><h3>${esc(j.name)}</h3><p>${esc(j.description||"No description")}<br>${esc(j.location_text||"")}</p><button class="primary" onclick="requestJoin('${j.id}',this)">Request to Join</button></div>`).join("")||`<div class="empty">No public jobs.</div>`}<div class="actions"><button class="secondary" onclick="this.closest('dialog').close()">Close</button></div>`;document.body.append(d);d.showModal()}
async function requestJoin(id,b){let msg=prompt("Optional message to employer:")||null;let r=await db.from("job_join_requests").insert({job_id:id,worker_id:S.user.id,message:msg});if(r.error)return toast(r.error.message,true);b.disabled=true;b.textContent="Request Sent"}
async function joinCode(){let c=document.getElementById("code").value.trim().toUpperCase();if(!c)return toast("Enter a code.",true);let r=await db.rpc("join_private_job",{p_join_code:c});if(r.error)return toast(r.error.message,true);await load();S.job=S.jobs.find(x=>x.id===r.data);render();toast("Joined job.")}
async function createTask(){let t=document.getElementById("tt").value.trim(),w=document.getElementById("tw").value,p=+document.getElementById("tp").value||0;if(!t||!w)return toast("Enter a title and choose a worker.",true);let r=await db.from("tasks").insert({job_id:S.job.id,assigned_worker_id:w,created_by:S.user.id,title:t,description:document.getElementById("td").value.trim()||null,pay_amount:p});if(r.error)return toast(r.error.message,true);render();toast("Task assigned.")}
async function completeTask(id){let r=await db.from("tasks").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",id).eq("assigned_worker_id",S.user.id);if(r.error)return toast(r.error.message,true);render();toast("Marked complete.")}
async function approveTask(id){let r=await db.from("tasks").update({status:"approved",approved_at:new Date().toISOString(),approved_by:S.user.id}).eq("id",id).eq("job_id",S.job.id);if(r.error)return toast(r.error.message,true);render();toast("Task approved.")}
async function saveJob(){let r=await db.from("jobs").update({name:document.getElementById("en").value.trim(),description:document.getElementById("ed").value.trim()||null,visibility:document.getElementById("ev").value}).eq("id",S.job.id).select().single();if(r.error)return toast(r.error.message,true);S.job=r.data;S.jobs=S.jobs.map(j=>j.id===r.data.id?r.data:j);render();toast("Saved.")}
const originalRender=render;
render=async function(){
  theme();
  if(!S.user||!S.profile){
    app.innerHTML=S.need2fa?codeScreen():S.user?setup():auth();
    return;
  }
  app.innerHTML=wrap(S.profile.role==="manager"?manager():worker());
  if(S.job){
    if(S.profile.role==="manager"&&S.tab==="home")await loadManagerHome();
    if(S.profile.role==="manager"&&S.tab==="workers")await loadWorkers();
    if(S.profile.role==="manager"&&S.tab==="requests")await loadRequests();
    if(S.profile.role==="manager"&&S.tab==="tasks")await loadTasks();
    if(S.profile.role==="worker"&&S.tab==="home"){await loadWorkerHome();await loadWSchedule()}
    if(S.profile.role==="manager"&&S.tab==="schedule")await loadSchedule();
    if(S.profile.role==="manager"&&S.tab==="payroll")await loadPayroll();
    if(S.profile.role==="worker"&&S.tab==="schedule")await loadWSchedule();
    if(S.profile.role==="worker"&&S.tab==="pay")await loadWPay();
    if(S.profile.role==="worker"&&S.tab==="history"){let b=document.getElementById("wbox");if(b)b.innerHTML=await whistoryData()}
    if(S.profile.role==="worker"&&S.tab==="tasks"){let b=document.getElementById("wbox");if(b)b.innerHTML=await wtasksData()}
  }
}

async function needMfa(){try{let a=await db.auth.mfa.getAuthenticatorAssuranceLevel();return !!(a.data&&a.data.nextLevel==="aal2"&&a.data.currentLevel!=="aal2")}catch(e){return false}}
function codeScreen(){return `<div class="auth"><div class="hero"><div class="logo">🔐</div><h1>Enter Code</h1><p>Open your authenticator app and enter the 6-digit code for TimeClock.</p></div>
<div class="card">${banner()}<label>6-digit code</label><input id="mcode" type="text" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="123456">
<div class="actions"><button class="primary" onclick="verifyLogin()">Verify</button><button class="secondary" onclick="logout()">Cancel</button></div></div></div>`}
async function verifyLogin(){let code=(document.getElementById("mcode").value||"").trim();if(code.length!==6)return toast("Enter the 6-digit code.",true);let l=await db.auth.mfa.listFactors();let f=((l.data&&l.data.totp)||[]).find(x=>x.status==="verified");if(!f)return toast("No 2FA found. Sign out and try again.",true);let c=await db.auth.mfa.challenge({factorId:f.id});if(c.error)return toast(friendly(c.error.message),true);let v=await db.auth.mfa.verify({factorId:f.id,challengeId:c.data.id,code});if(v.error)return toast("Wrong code. Try again.",true);await load();render()}
async function mfaDialog(){
 let l=await db.auth.mfa.listFactors();if(l.error)return toast(friendly(l.error.message),true);
 let f=((l.data&&l.data.totp)||[]).find(x=>x.status==="verified");
 let d=document.createElement("dialog");
 d.innerHTML=f?`<h2>🔐 2FA is ON</h2><p>Your account asks for an authenticator code every time you sign in.</p><div class="actions"><button class="danger" id="mfaoff">Turn Off 2FA</button><button class="secondary" id="mfax">Close</button></div>`
 :`<h2>🔐 Set Up 2FA</h2><p>Adds a 6-digit code from an authenticator app (Google Authenticator, Microsoft Authenticator, or Authy) every time you sign in.</p><div id="mfabody"><div class="actions"><button class="primary" id="mfaon">Start Setup</button><button class="secondary" id="mfax">Close</button></div></div>`;
 document.body.append(d);d.showModal();
 const close=()=>{d.close();d.remove()};
 d.querySelector("#mfax").onclick=close;
 if(f){d.querySelector("#mfaoff").onclick=async()=>{let r=await db.auth.mfa.unenroll({factorId:f.id});close();if(r.error)return toast(friendly(r.error.message),true);toast("2FA turned off.")};return}
 d.querySelector("#mfaon").onclick=async()=>{
  for(let x of ((l.data&&l.data.all)||[]).filter(x=>x.status==="unverified")){await db.auth.mfa.unenroll({factorId:x.id})}
  let e=await db.auth.mfa.enroll({factorType:"totp",friendlyName:"TimeClock "+Date.now()});
  if(e.error){close();return toast(friendly(e.error.message),true)}
  d.querySelector("#mfabody").innerHTML=`<p>1. Scan this code with your authenticator app.</p><div style="text-align:center;background:#fff;padding:8px;border-radius:10px"><img src="${e.data.totp.qr_code}" alt="QR code" style="width:200px;height:200px"></div><p class="small">Can't scan? Type this key into the app: <b style="word-break:break-all;user-select:all">${esc(e.data.totp.secret)}</b></p><p>2. Enter the 6-digit code it shows.</p><input id="mfac" type="text" inputmode="numeric" maxlength="6" placeholder="123456"><div class="actions"><button class="primary" id="mfav">Turn On 2FA</button><button class="secondary" id="mfax2">Cancel</button></div>`;
  d.querySelector("#mfax2").onclick=async()=>{await db.auth.mfa.unenroll({factorId:e.data.id});close()};
  d.querySelector("#mfav").onclick=async()=>{let code=d.querySelector("#mfac").value.trim();if(code.length!==6)return alert("Enter the 6-digit code.");let c=await db.auth.mfa.challenge({factorId:e.data.id});if(c.error)return alert(friendly(c.error.message));let v=await db.auth.mfa.verify({factorId:e.data.id,challengeId:c.data.id,code});if(v.error)return alert("Wrong code. Check your app and try again.");close();toast("2FA is on. You'll need a code next time you sign in.")}
 }
}
function secCard(){return `<div class="card"><h2>🔐 Two-Factor Authentication</h2><p>Protect your account with a 6-digit code from an authenticator app.</p><div class="actions"><button class="primary" onclick="mfaDialog()">Manage 2FA</button></div></div>`}
const _ms=msettings,_ws=wsettings;
msettings=function(){return _ms()+secCard()};
wsettings=function(){return _ws()+secCard()};

/* ===== Schedules + Payroll ===== */
const ymd=d=>new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,10);
function whistory(){return `<div id="wbox" class="card">Loading...</div>`}
function wtasks(){return `<div id="wbox" class="card">Loading...</div>`}
async function actWorkers(){let m=await db.from("job_workers").select("id,worker_id,status,hourly_rate").eq("job_id",S.job.id);let all=m.data||[];let ids=all.map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};return{rows:all.filter(x=>x.status==="active"),names:new Map((p.data||[]).map(x=>[x.id,x.name]))}}
const back=`<button class="secondary" onclick="S.job=null;render()">← Jobs</button>`;
function mschedule(){return `<div class="row"><div><h1>🗓️ Schedule</h1><p>Assign shifts to your workers.</p></div>${back}</div><div class="card"><h2>New Shift</h2><label>Worker</label><select id="sw"><option value="">Choose worker</option></select><label>Date</label><input id="sd" type="date" value="${ymd(new Date())}"><label>Start</label><input id="ss" type="time" value="09:00"><label>End</label><input id="se" type="time" value="17:00"><label>Notes</label><input id="sn" placeholder="Optional"><div class="actions"><button class="primary" onclick="addShift()">Add Shift</button></div></div><div class="card"><h2>Upcoming Shifts</h2><div id="sl">Loading...</div></div>`}
async function loadSchedule(){let {rows,names}=await actWorkers();let sel=document.getElementById("sw");if(sel)sel.innerHTML=`<option value="">Choose worker</option>`+rows.map(x=>`<option value="${x.worker_id}">${esc(names.get(x.worker_id)||"Worker")}</option>`).join("");let r=await db.from("shifts").select("*").eq("job_id",S.job.id).gte("end_time",new Date(Date.now()-864e5).toISOString()).order("start_time");document.getElementById("sl").innerHTML=r.error?`<div class="empty">${esc(r.error.message)}</div>`:(r.data||[]).map(x=>`<div class="item row"><div><b>${esc(names.get(x.worker_id)||"Worker")}</b><div class="small">${date(x.start_time)} → ${date(x.end_time)}${x.notes?" · "+esc(x.notes):""}</div></div><button class="danger" onclick="delShift('${x.id}')">Delete</button></div>`).join("")||`<div class="empty">No shifts yet.</div>`}
async function addShift(){let g=i=>document.getElementById(i).value,w=g("sw"),d=g("sd"),s=g("ss"),e=g("se");if(!w||!d||!s||!e)return toast("Choose a worker, date, start and end.",true);let st=new Date(d+"T"+s),en=new Date(d+"T"+e);if(en<=st)en=new Date(en.getTime()+864e5);let r=await db.from("shifts").insert({job_id:S.job.id,worker_id:w,start_time:st.toISOString(),end_time:en.toISOString(),notes:g("sn").trim()||null});if(r.error)return toast(r.error.message,true);render();toast("Shift added.")}
async function delShift(id){if(!confirm("Delete this shift?"))return;let r=await db.from("shifts").delete().eq("id",id);if(r.error)return toast(r.error.message,true);render()}
function mpayroll(){let t=new Date();return `<div class="row"><div><h1>💵 Payroll</h1><p>Set pay rates, then generate paychecks from hours and approved tasks.</p></div>${back}</div><div class="card"><h2>Hourly Rates</h2><div id="pr">Loading...</div></div><div class="card"><h2>Generate Paychecks</h2><label>Period start</label><input id="ps" type="date" value="${ymd(new Date(t-6*864e5))}"><label>Period end</label><input id="pe" type="date" value="${ymd(t)}"><div class="actions"><button class="primary" onclick="genPay()">Generate</button></div></div><div class="card"><h2>Paychecks</h2><div id="pl">Loading...</div></div>`}
async function loadPayroll(){let {rows,names}=await actWorkers();document.getElementById("pr").innerHTML=rows.map(x=>`<div class="item row"><b>${esc(names.get(x.worker_id)||"Worker")}</b><div class="row"><input id="rate_${x.id}" type="number" min="0" step=".01" value="${x.hourly_rate||0}" style="width:100px"><button class="secondary" onclick="saveRate('${x.id}')">Save</button></div></div>`).join("")||`<div class="empty">No workers yet.</div>`;let r=await db.from("paychecks").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});document.getElementById("pl").innerHTML=r.error?`<div class="empty">${esc(r.error.message)}</div>`:(r.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(names.get(x.worker_id)||"Worker")}</b><span class="badge">${x.status}</span></div><p>${x.period_start} → ${x.period_end}<br>${Number(x.hours).toFixed(2)}h × ${money(x.hourly_rate)} + tasks ${money(x.task_pay)}<br><b>Total ${money(x.total)}</b></p><div class="actions">${x.status==="pending"?`<button class="success" onclick="markPaid('${x.id}')">Mark Paid</button><button class="danger" onclick="delPay('${x.id}')">Delete</button>`:`<span class="small">Paid ${date(x.paid_at)}</span>`}</div></div>`).join("")||`<div class="empty">No paychecks yet.</div>`}
async function saveRate(id){let v=+document.getElementById("rate_"+id).value||0;let r=await db.from("job_workers").update({hourly_rate:v}).eq("id",id);if(r.error)return toast(r.error.message,true);toast("Rate saved.")}
async function genPay(){let s=document.getElementById("ps").value,e=document.getElementById("pe").value;if(!s||!e||e<s)return toast("Pick a valid period.",true);let from=new Date(s+"T00:00").toISOString(),to=new Date(new Date(e+"T00:00").getTime()+864e5).toISOString();let {rows}=await actWorkers(),made=0;for(let w of rows){let ex=await db.from("paychecks").select("id").eq("job_id",S.job.id).eq("worker_id",w.worker_id).eq("period_start",s).eq("period_end",e).limit(1);if(ex.data&&ex.data.length)continue;let t=await db.from("time_records").select("clock_in,clock_out").eq("job_id",S.job.id).eq("worker_id",w.worker_id).gte("clock_in",from).lt("clock_in",to).not("clock_out","is",null);let h=Math.round((t.data||[]).reduce((a,x)=>a+(new Date(x.clock_out)-new Date(x.clock_in))/36e5,0)*100)/100;let k=await db.from("tasks").select("pay_amount").eq("job_id",S.job.id).eq("assigned_worker_id",w.worker_id).eq("status","approved").gte("approved_at",from).lt("approved_at",to);let tp=(k.data||[]).reduce((a,x)=>a+Number(x.pay_amount||0),0);if(!h&&!tp)continue;let rate=Number(w.hourly_rate||0);let r=await db.from("paychecks").insert({job_id:S.job.id,worker_id:w.worker_id,period_start:s,period_end:e,hours:h,hourly_rate:rate,task_pay:tp,total:Math.round((h*rate+tp)*100)/100});if(r.error)return toast(r.error.message,true);made++}render();toast(made?made+" paycheck(s) created.":"Nothing to pay for that period.")}
async function markPaid(id){let r=await db.from("paychecks").update({status:"paid",paid_at:new Date().toISOString()}).eq("id",id);if(r.error)return toast(r.error.message,true);render();toast("Marked paid.")}
async function delPay(id){if(!confirm("Delete this paycheck?"))return;let r=await db.from("paychecks").delete().eq("id",id);if(r.error)return toast(r.error.message,true);render()}
function wpay(){return `<div class="row"><h1>💵 My Pay</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card" id="wpl">Loading...</div>`}
async function loadWPay(){let r=await db.from("paychecks").select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id).order("created_at",{ascending:false});document.getElementById("wpl").innerHTML=r.error?`<div class="empty">${esc(r.error.message)}</div>`:(r.data||[]).map(x=>`<div class="item"><div class="row"><b>${x.period_start} → ${x.period_end}</b><span class="badge">${x.status}</span></div><p>${Number(x.hours).toFixed(2)}h × ${money(x.hourly_rate)} + tasks ${money(x.task_pay)}<br><b>Total ${money(x.total)}</b></p></div>`).join("")||`<div class="empty">No paychecks yet.</div>`}

/* ===== Worker schedule: week/day view with hours ===== */
const hm=h=>{let m=Math.round(h*60);return Math.floor(m/60)+"h "+(m%60)+"m"};
const tm=x=>new Date(x).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
function wRange(){let a=new Date(+(S.sd||Date.now()));a.setHours(0,0,0,0);let wk=(S.sv||"week")==="week";if(wk)a.setDate(a.getDate()-(a.getDay()+6)%7);let b=new Date(a);b.setDate(b.getDate()+(wk?7:1));return{a,b,wk}}
function wShift(n){let d=new Date(+(S.sd||Date.now()));d.setDate(d.getDate()+n*((S.sv||"week")==="week"?7:1));S.sd=+d;render()}
function wToday(){S.sd=Date.now();render()}
function wView(v){S.sv=v;render()}
function wschedBlock(){let wk=(S.sv||"week")==="week";return `<div class="card"><div class="row"><b id="wrange"></b><div class="actions" style="margin:0"><button class="${wk?"primary":"secondary"}" onclick="wView('week')">Week</button><button class="${wk?"secondary":"primary"}" onclick="wView('day')">Day</button></div></div><div class="actions"><button class="secondary" onclick="wShift(-1)">‹ Prev</button><button class="secondary" onclick="wToday()">Today</button><button class="secondary" onclick="wShift(1)">Next ›</button></div><div id="wsum" class="small" style="margin-top:10px"></div></div><div id="wsl">Loading...</div>`}
function wschedule(){return `<div class="row"><h1>🗓️ My Schedule</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div>`+wschedBlock()}
const _wh=whome;whome=function(){return _wh()+wschedBlock()};
async function loadWSchedule(){let {a,b,wk}=wRange(),q=t=>db.from(t).select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id);
let sh=await q("shifts").gte("start_time",a.toISOString()).lt("start_time",b.toISOString()).order("start_time");
let tr=await q("time_records").gte("clock_in",a.toISOString()).lt("clock_in",b.toISOString()).order("clock_in");
if(sh.error||tr.error){document.getElementById("wsl").innerHTML=`<div class="card empty">${esc((sh.error||tr.error).message)}</div>`;return}
let now=Date.now(),sched=0,done=0,html="";
for(let d=new Date(a);d<b;d.setDate(d.getDate()+1)){let e=new Date(d);e.setDate(e.getDate()+1);
 let ds=(sh.data||[]).filter(x=>new Date(x.start_time)>=d&&new Date(x.start_time)<e);
 let rs=(tr.data||[]).filter(x=>new Date(x.clock_in)>=d&&new Date(x.clock_in)<e);
 let req=ds.reduce((t,x)=>t+(new Date(x.end_time)-new Date(x.start_time))/36e5,0);
 let wh=rs.reduce((t,x)=>t+((x.clock_out?new Date(x.clock_out):now)-new Date(x.clock_in))/36e5,0);
 sched+=req;done+=wh;
 html+=`<div class="card"><div class="row"><b>${d.toLocaleDateString([],{weekday:"long",month:"short",day:"numeric"})}</b>${d.toDateString()===new Date().toDateString()?`<span class="badge">Today</span>`:""}</div>${ds.map(x=>`<p>🗓️ ${tm(x.start_time)} – ${tm(x.end_time)} · <b>${hm((new Date(x.end_time)-new Date(x.start_time))/36e5)} required</b>${x.notes?" · "+esc(x.notes):""}</p>`).join("")||`<p>No shift scheduled.</p>`}<p>⏱️ Worked: <b>${hm(wh)}</b>${req?" of "+hm(req):""}</p>${wk?"":rs.map(x=>`<div class="small">${tm(x.clock_in)} → ${x.clock_out?tm(x.clock_out):"still working"}</div>`).join("")}</div>`}
let last=new Date(b.getFullYear(),b.getMonth(),b.getDate()-1),f=x=>x.toLocaleDateString([],{month:"short",day:"numeric"});
document.getElementById("wrange").textContent=wk?f(a)+" – "+f(last):a.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"});
document.getElementById("wsum").innerHTML=`Total worked: <b>${hm(done)}</b> · Scheduled: <b>${hm(sched)}</b>`;
document.getElementById("wsl").innerHTML=html}
