const URL="https://lhxgfstmzdbpkmyytbse.supabase.co";
const KEY="sb_publishable_HZiFjnZZAsHyECLha2LM9g_cBB3WDUe";
const db=supabase.createClient(URL,KEY);
const app=document.getElementById("app");
let S={user:null,profile:null,jobs:[],job:null,tab:"home",msg:"",err:""};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=x=>"$"+Number(x||0).toFixed(2);
const date=x=>x?new Date(x).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"—";
const mins=(a,b=new Date())=>Math.max(0,Math.floor((new Date(b)-new Date(a))/60000));
const dur=(a,b)=>{let m=mins(a,b);return `${Math.floor(m/60)}h ${m%60}m`};
function theme(){let t=localStorage.tcTheme||"system";document.documentElement.dataset.theme=t==="system"?(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"):t}
function toast(x,e=false){S.msg=e?"":x;S.err=e?x:"";render();setTimeout(()=>{S.msg=S.err="";render()},3000)}
async function load(){
 const {data:{user}}=await db.auth.getUser();S.user=user;
 if(!user){S.profile=null;return}
 const p=await db.from("profiles").select("*").eq("id",user.id).single();
 S.profile=p.data;
 if(S.profile?.role==="manager"){let r=await db.from("jobs").select("*").eq("owner_id",user.id).order("created_at",{ascending:false});S.jobs=r.data||[]}
 else {let r=await db.from("job_workers").select("job_id,status,jobs(*)").eq("worker_id",user.id);S.jobs=(r.data||[]).filter(x=>x.status==="active"&&x.jobs).map(x=>x.jobs)}
}
async function boot(){theme();await load();render();db.auth.onAuthStateChange(()=>setTimeout(async()=>{await load();render()},0))}
boot();

function auth(){
return `<div class="auth"><div class="hero"><div class="logo">⏱️</div><h1>TimeClock</h1><p>Track shifts, tasks, requests, and jobs.</p></div>
<div class="card"><h2>Sign in</h2><label>Email</label><input id="email" type="email">
<label>Password</label><input id="pass" type="password">
<label>Account type</label><select id="role"><option value="worker">👷 Worker</option><option value="manager">👑 Manager / Employer</option></select>
<div class="actions"><button class="primary" onclick="login()">Sign In</button><button class="secondary" onclick="signup()">Create Account</button></div>
<p class="small">Supabase securely handles your password.</p></div></div>`}
function wrap(c){
return `<div class="app"><div class="row"><div><b>⏱️ TimeClock</b><div class="small">${esc(S.profile?.name)} · ${S.profile?.role}</div></div>
<div class="actions"><button class="secondary" onclick="cycleTheme()">🌙 Theme</button><button class="secondary" onclick="logout()">Sign Out</button></div></div>
${S.msg?`<div class="notice">${esc(S.msg)}</div>`:""}${S.err?`<div class="error">${esc(S.err)}</div>`:""}${c}</div>`}
function render(){theme();if(!S.user||!S.profile){app.innerHTML=auth();return}app.innerHTML=wrap(S.profile.role==="manager"?manager():worker())}
async function login(){let email=emailEl().value.trim(),pass=passEl().value;if(!email||!pass)return toast("Enter email and password.",true);let r=await db.auth.signInWithPassword({email,password:pass});if(r.error)return toast(r.error.message,true);toast("Signed in.")}
async function signup(){let email=emailEl().value.trim(),pass=passEl().value,role=document.getElementById("role").value;if(!email||pass.length<6)return toast("Use an email and a password of at least 6 characters.",true);let r=await db.auth.signUp({email,password:pass});if(r.error)return toast(r.error.message,true);if(!r.data.user)return toast("Check your email to finish signup.");let name=prompt("What name should TimeClock show?");if(!name)return toast("Finish signup, then sign in to complete your profile.");let p=await db.from("profiles").insert({id:r.data.user.id,name:name.trim(),role}).select().single();if(p.error)return toast(p.error.message,true);S.profile=p.data;render()}
const emailEl=()=>document.getElementById("email"),passEl=()=>document.getElementById("pass");
async function logout(){await db.auth.signOut();S={user:null,profile:null,jobs:[],job:null,tab:"home",msg:"",err:""};render()}
function cycleTheme(){let t=localStorage.tcTheme||"system";localStorage.tcTheme=t==="system"?"dark":t==="dark"?"light":"system";theme();render()}
function chooseJob(id){S.job=S.jobs.find(x=>x.id===id);S.tab="home";render();if(S.profile.role==="manager")loadManagerHome()}
function manager(){
if(!S.job)return wrapInner(`<div class="hero"><h1>👑 Manager</h1><p>Choose a job or create one.</p></div>
<div class="grid">${S.jobs.map(j=>`<div class="card"><h2>${esc(j.name)}</h2><p>${esc(j.description||"")}</p><span class="badge">${j.visibility==="public"?"🌎 Public":"🔒 Private"}</span><div class="actions"><button class="primary" onclick="chooseJob('${j.id}')">Open</button></div></div>`).join("")||`<div class="card empty">No jobs yet.</div>`}</div>
<div class="card"><h2>Create Job</h2><label>Name</label><input id="jn" placeholder="Example: JB's Landscaping"><label>Description</label><textarea id="jd"></textarea><label>Visibility</label><select id="jv"><option value="private">🔒 Private</option><option value="public">🌎 Public</option></select><label>Location / area</label><input id="jl" placeholder="Optional"><div class="actions"><button class="primary" onclick="createJob()">Create Job</button></div></div>`);
let nav=["home","workers","requests","tasks","settings"],labels=["🏠 Home","👥 Workers","📋 Requests","💰 Tasks","⚙️ Settings"];
return wrapInner(`<div class="tabs">${nav.map((x,i)=>`<button class="${S.tab===x?"primary":"secondary"}" onclick="S.tab='${x}';render()">${labels[i]}</button>`).join("")}</div>
${S.tab==="home"?mhome():S.tab==="workers"?mworkers():S.tab==="requests"?mrequests():S.tab==="tasks"?mtasks():msettings()}`)}
function wrapInner(x){return x}
function mhome(){return `<div class="row"><div><h1>${esc(S.job.name)}</h1><p>${esc(S.job.description||"")}</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div>
<div class="grid"><div class="stat">👥<b id="wc">...</b>Workers</div><div class="stat">🟢<b id="ww">...</b>Working</div><div class="stat">📋<b id="rq">...</b>Requests</div></div>
<div class="card"><h2>Who's Working?</h2><div id="who">Loading...</div></div>`}
async function loadManagerHome(){let j=S.job;let m=await db.from("job_workers").select("worker_id,status").eq("job_id",j.id);let ids=(m.data||[]).filter(x=>x.status==="active").map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let o=ids.length?await db.from("time_records").select("worker_id,clock_in").eq("job_id",j.id).is("clock_out",null):{data:[]};let q=await db.from("time_change_requests").select("*",{count:"exact",head:true}).eq("job_id",j.id).eq("status","pending");document.getElementById("wc").textContent=ids.length;document.getElementById("ww").textContent=(o.data||[]).length;document.getElementById("rq").textContent=q.count||0;let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("who").innerHTML=(m.data||[]).filter(x=>x.status==="active").map(x=>{let r=(o.data||[]).find(y=>y.worker_id===x.worker_id);return `<div class="item row"><div><b>${esc(map.get(x.worker_id)||"Worker")}</b><div class="small">${r?"Started "+date(r.clock_in):"Not working"}</div></div><span class="status ${r?"working":""}">${r?dur(r.clock_in):"Not Working"}</span></div>`}).join("")||`<div class="empty">No workers yet.</div>`}
function mworkers(){return `<div class="row"><div><h1>Workers</h1><p>Current and former workers.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div>
<div class="card"><h2>Join Code</h2><div class="code">${esc(S.job.join_code||"")}</div><div class="actions"><button class="secondary" onclick="navigator.clipboard.writeText('${esc(S.job.join_code)}');toast('Copied')">Copy</button><button class="secondary" onclick="regen()">Regenerate</button></div></div>
<div class="card"><h2>Workers</h2><div id="wl">Loading...</div></div>`}
async function loadWorkers(){let m=await db.from("job_workers").select("*").eq("job_id",S.job.id).order("joined_at",{ascending:false});let ids=(m.data||[]).map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("wl").innerHTML=(m.data||[]).map(x=>`<div class="item row"><div><b>${esc(map.get(x.worker_id)||"Worker")}</b><div class="small">${x.status}</div></div>${x.status==="active"?`<button class="danger" onclick="removeWorker('${x.id}')">Remove</button>`:`<button class="success" onclick="restore('${x.id}')">Restore</button>`}</div>`).join("")||`<div class="empty">No workers.</div>`}
function mrequests(){return `<div class="row"><div><h1>Requests</h1><p>Review custom times and public-job join requests.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><h2>Time Requests</h2><div id="trs">Loading...</div></div><div class="card"><h2>Join Requests</h2><div id="jrs">Loading...</div></div>`}
async function loadRequests(){let r=await db.from("time_change_requests").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});let ids=[...new Set((r.data||[]).map(x=>x.worker_id))];let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("trs").innerHTML=(r.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(map.get(x.worker_id)||"Worker")}</b><span class="badge">${x.status}</span></div><p>${x.request_type} → ${date(x.requested_time)}<br>${esc(x.reason||"No description provided.")}</p>${x.status==="pending"?`<div class="actions"><button class="success" onclick="reviewTime('${x.id}','approved')">Approve</button><button class="danger" onclick="reviewTime('${x.id}','denied')">Deny</button></div>`:""}</div>`).join("")||`<div class="empty">No requests.</div>`;
let jr=await db.from("job_join_requests").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});let ids2=[...new Set((jr.data||[]).map(x=>x.worker_id))];let p2=ids2.length?await db.from("profiles").select("id,name").in("id",ids2):{data:[]};let map2=new Map((p2.data||[]).map(x=>[x.id,x.name]));document.getElementById("jrs").innerHTML=(jr.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(map2.get(x.worker_id)||"Worker")}</b><span class="badge">${x.status}</span></div><p>${esc(x.message||"No message.")}</p>${x.status==="pending"?`<div class="actions"><button class="success" onclick="reviewJoin('${x.id}','approved','${x.worker_id}')">Approve</button><button class="danger" onclick="reviewJoin('${x.id}','denied')">Deny</button></div>`:""}</div>`).join("")||`<div class="empty">No join requests.</div>`}
function mtasks(){return `<div class="row"><div><h1>💰 Paid Tasks</h1><p>Assign extra paid work.</p></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><h2>New Task</h2><label>Title</label><input id="tt"><label>Description</label><textarea id="td"></textarea><label>Pay</label><input id="tp" type="number" min="0" step=".01"><label>Worker</label><select id="tw"><option value="">Choose worker</option></select><div class="actions"><button class="primary" onclick="createTask()">Assign Task</button></div></div><div class="card"><h2>Tasks</h2><div id="tl">Loading...</div></div>`}
async function loadTasks(){let m=await db.from("job_workers").select("worker_id").eq("job_id",S.job.id).eq("status","active");let ids=(m.data||[]).map(x=>x.worker_id);let p=ids.length?await db.from("profiles").select("id,name").in("id",ids):{data:[]};let map=new Map((p.data||[]).map(x=>[x.id,x.name]));document.getElementById("tw").innerHTML=`<option value="">Choose worker</option>`+(p.data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");let t=await db.from("tasks").select("*").eq("job_id",S.job.id).order("created_at",{ascending:false});document.getElementById("tl").innerHTML=(t.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(x.title)}</b><span class="badge">${x.status}</span></div><p>${esc(x.description||"")}<br>${money(x.pay_amount)} · ${esc(map.get(x.assigned_worker_id)||"Unassigned")}</p>${x.status==="completed"?`<button class="success" onclick="approveTask('${x.id}')">Approve</button>`:""}</div>`).join("")||`<div class="empty">No tasks.</div>`}
function msettings(){return `<div class="row"><div><h1>Settings</h1></div><button class="secondary" onclick="S.job=null;render()">← Jobs</button></div><div class="card"><label>Job name</label><input id="en" value="${esc(S.job.name)}"><label>Description</label><textarea id="ed">${esc(S.job.description||"")}</textarea><label>Visibility</label><select id="ev"><option value="private" ${S.job.visibility==="private"?"selected":""}>🔒 Private</option><option value="public" ${S.job.visibility==="public"?"selected":""}>🌎 Public</option></select><button class="primary" onclick="saveJob()">Save</button></div>`}
function worker(){if(!S.job)return wrapInner(`<div class="hero"><h1>👷 Welcome, ${esc(S.profile.name)}</h1><p>Open a job or browse public jobs.</p></div><div class="card"><h2>My Jobs</h2><div class="grid">${S.jobs.map(j=>`<div class="card"><h3>${esc(j.name)}</h3><p>${esc(j.description||"")}</p><button class="primary" onclick="chooseJob('${j.id}')">Open</button></div>`).join("")||`<div class="empty">No jobs yet.</div>`}</div></div><div class="card"><h2>🔎 Browse Jobs</h2><button class="primary" onclick="browse()">Browse Public Jobs</button></div><div class="card"><h2>🔑 Private Job</h2><input id="code" placeholder="Job code"><button class="secondary" onclick="joinCode()">Join with Code</button></div>`);
let nav=["home","history","tasks","settings"],lab=["🏠 Home","📅 History","💰 Tasks","⚙️ Settings"];return wrapInner(`<div class="tabs">${nav.map((x,i)=>`<button class="${S.tab===x?"primary":"secondary"}" onclick="S.tab='${x}';render()">${lab[i]}</button>`).join("")}</div>${S.tab==="home"?whome():S.tab==="history"?whistory():S.tab==="tasks"?wtasks():wsettings()}`)}
function whome(){return `<div class="row"><div><h1>${esc(S.job.name)}</h1><p>${esc(S.job.description||"")}</p></div><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card" id="clockCard">Loading...</div>`}
async function loadWorkerHome(){let r=await db.from("time_records").select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id).is("clock_out",null).limit(1);let x=r.data?.[0];document.getElementById("clockCard").innerHTML=`<div style="text-align:center"><span class="status ${x?"working":""}">${x?"🟢 Working":"⚪ Not Working"}</span><h2>${x?dur(x.clock_in):"Ready to work"}</h2><p>${x?"Clocked in "+date(x.clock_in):"Clock in now or request a custom time."}</p><div class="actions" style="justify-content:center">${x?`<button class="danger big" onclick="clockOut('${x.id}')">⏹ Clock Out Now</button><button class="secondary big" onclick="custom('clock_out','${x.id}')">🕐 Request Custom Clock Out</button>`:`<button class="success big" onclick="clockIn()">▶ Clock In Now</button><button class="secondary big" onclick="custom('clock_in','')">🕐 Request Custom Clock In</button>`}</div></div>`}
async function whistory(){let r=await db.from("time_records").select("*").eq("job_id",S.job.id).eq("worker_id",S.user.id).order("clock_in",{ascending:false}).limit(50);return `<div class="row"><h1>History</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card">${(r.data||[]).map(x=>`<div class="item row"><div><b>${date(x.clock_in)}</b><div class="small">${x.clock_out?dur(x.clock_in,x.clock_out):"Still working"}${x.manager_edited?" · Manager approved edit":""}</div></div></div>`).join("")||`<div class="empty">No shifts.</div>`}</div>`}
async function wtasks(){let t=await db.from("tasks").select("*").eq("job_id",S.job.id).eq("assigned_worker_id",S.user.id).order("created_at",{ascending:false});return `<div class="row"><h1>💰 Tasks</h1><button class="secondary" onclick="S.job=null;load();render()">← My Jobs</button></div><div class="card">${(t.data||[]).map(x=>`<div class="item"><div class="row"><b>${esc(x.title)}</b><span class="badge">${x.status}</span></div><p>${esc(x.description||"")}<br><b>${money(x.pay_amount)}</b></p>${x.status==="assigned"?`<button class="primary" onclick="completeTask('${x.id}')">Mark Complete</button>`:""}</div>`).join("")||`<div class="empty">No tasks.</div>`}</div>`}
function wsettings(){return `<div class="card"><h1>Settings</h1><select onchange="localStorage.tcTheme=this.value;theme();render()"><option>system</option><option>light</option><option>dark</option></select></div>`}
async function createJob(){let n=document.getElementById("jn").value.trim();if(!n)return toast("Enter a job name.",true);let r=await db.from("jobs").insert({owner_id:S.user.id,name:n,description:document.getElementById("jd").value.trim()||null,visibility:document.getElementById("jv").value,location_text:document.getElementById("jl").value.trim()||null,join_code:codegen()}).select().single();if(r.error)return toast(r.error.message,true);S.jobs.unshift(r.data);S.job=r.data;render()}
function codegen(){let a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",s="";for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];return s.slice(0,3)+"-"+s.slice(3)}
async function regen(){let r=await db.from("jobs").update({join_code:codegen()}).eq("id",S.job.id).select().single();if(r.error)return toast(r.error.message,true);S.job=r.data;S.jobs=S.jobs.map(j=>j.id===r.data.id?r.data:j);render();toast("New join code created.")}
async function removeWorker(id){if(!confirm("Remove this worker? Their history stays."))return;let r=await db.from("job_workers").update({status:"inactive",left_at:new Date().toISOString()}).eq("id",id);if(r.error)return toast(r.error.message,true);render()}
async function restore(id){let r=await db.from("job_workers").update({status:"active",left_at:null}).eq("id",id);if(r.error)return toast(r.error.message,true);render()}
async function reviewJoin(id,status,wid){let r=await db.from("job_join_requests").update({status,reviewed_by:S.user.id,reviewed_at:new Date().toISOString()}).eq("id",id).select().single();if(r.error)return toast(r.error.message,true);if(status==="approved"){let x=await db.from("job_workers").upsert({job_id:S.job.id,worker_id:wid,status:"active"},{onConflict:"job_id,worker_id"});if(x.error)return toast(x.error.message,true)}render();toast(status==="approved"?"Worker approved.":"Denied.")}
async function reviewTime(id,status){let r=await db.from("time_change_requests").update({status,reviewed_by:S.user.id,reviewed_at:new Date().toISOString()}).eq("id",id).select().single();if(r.error)return toast(r.error.message,true);if(status==="approved"){let x=r.data;if(x.time_record_id){let field=x.request_type==="clock_in"?"clock_in":"clock_out";let u=await db.from("time_records").update({[field]:x.requested_time,manager_edited:true,edited_by:S.user.id,edited_at:new Date().toISOString()}).eq("id",x.time_record_id);if(u.error)return toast(u.error.message,true)}else{let u=await db.from("time_records").insert({job_id:x.job_id,worker_id:x.worker_id,clock_in:x.requested_time,notes:x.reason||null,manager_edited:true,edited_by:S.user.id,edited_at:new Date().toISOString()});if(u.error)return toast(u.error.message,true)}}render();toast(status==="approved"?"Approved.":"Denied.")}
async function clockIn(){let r=await db.from("time_records").insert({job_id:S.job.id,worker_id:S.user.id,clock_in:new Date().toISOString()});if(r.error)return toast(r.error.message,true);render();toast("Clocked in.")}
async function clockOut(id){let r=await db.from("time_records").update({clock_out:new Date().toISOString()}).eq("id",id).eq("worker_id",S.user.id);if(r.error)return toast(r.error.message,true);render();toast("Clocked out.")}
function custom(type,record){let now=new Date(),h=now.getHours()%12||12,m=String(now.getMinutes()).padStart(2,"0"),ap=now.getHours()>=12?"PM":"AM",d=document.createElement("dialog");d.innerHTML=`<h2>Request Custom ${type==="clock_in"?"Clock In":"Clock Out"}</h2><p>Your employer must approve this request.</p><div class="picker"><select id="h">${Array.from({length:12},(_,i)=>`<option ${i+1==h?"selected":""}>${i+1}</option>`).join("")}</select><select id="m">${Array.from({length:60},(_,i)=>`<option ${String(i).padStart(2,"0")==m?"selected":""}>${String(i).padStart(2,"0")}</option>`).join("")}</select><select id="a"><option ${ap==="AM"?"selected":""}>AM</option><option ${ap==="PM"?"selected":""}>PM</option></select></div><label>Optional description</label><textarea id="reason" placeholder="Why do you need this time?"></textarea><div class="actions"><button class="primary" id="send">Submit Request</button><button class="secondary" onclick="this.closest('dialog').close()">Cancel</button></div>`;document.body.append(d);d.showModal();d.querySelector("#send").onclick=async()=>{let hh=+d.querySelector("#h").value%12;if(d.querySelector("#a").value==="PM")hh+=12;let dt=new Date();dt.setHours(hh,+d.querySelector("#m").value,0,0);let r=await db.from("time_change_requests").insert({job_id:S.job.id,worker_id:S.user.id,time_record_id:record||null,request_type:type,requested_time:dt.toISOString(),reason:d.querySelector("#reason").value.trim()||null});d.close();d.remove();if(r.error)return toast(r.error.message,true);toast("Request sent to your employer.")}
}
async function browse(){let r=await db.from("jobs").select("*").eq("visibility","public").eq("active",true).order("created_at",{ascending:false});if(r.error)return toast(r.error.message,true);let d=document.createElement("dialog");d.innerHTML=`<h2>🌎 Browse Jobs</h2>${(r.data||[]).map(j=>`<div class="item"><h3>${esc(j.name)}</h3><p>${esc(j.description||"No description")}<br>${esc(j.location_text||"")}</p><button class="primary" onclick="requestJoin('${j.id}',this)">Request to Join</button></div>`).join("")||`<div class="empty">No public jobs.</div>`}<div class="actions"><button class="secondary" onclick="this.closest('dialog').close()">Close</button></div>`;document.body.append(d);d.showModal()}
async function requestJoin(id,b){let msg=prompt("Optional message to employer:")||null;let r=await db.from("job_join_requests").insert({job_id:id,worker_id:S.user.id,message:msg});if(r.error)return toast(r.error.message,true);b.disabled=true;b.textContent="Request Sent"}
async function joinCode(){let c=document.getElementById("code").value.trim().toUpperCase();if(!c)return toast("Enter a code.",true);let r=await db.rpc("join_private_job",{p_join_code:c});if(r.error)return toast(r.error.message,true);await load();S.job=S.jobs.find(x=>x.id===r.data);render();toast("Joined job.")}
async function createTask(){let t=document.getElementById("tt").value.trim(),w=document.getElementById("tw").value,p=+document.getElementById("tp").value||0;if(!t||!w)return toast("Enter a title and choose a worker.",true);let r=await db.from("tasks").insert({job_id:S.job.id,assigned_worker_id:w,created_by:S.user.id,title:t,description:document.getElementById("td").value.trim()||null,pay_amount:p});if(r.error)return toast(r.error.message,true);render();toast("Task assigned.")}
async function completeTask(id){let r=await db.from("tasks").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",id).eq("assigned_worker_id",S.user.id);if(r.error)return toast(r.error.message,true);render();toast("Marked complete.")}
async function approveTask(id){let r=await db.from("tasks").update({status:"approved",approved_at:new Date().toISOString(),approved_by:S.user.id}).eq("id",id).eq("job_id",S.job.id);if(r.error)return toast(r.error.message,true);render();toast("Task approved.")}
async function saveJob(){let r=await db.from("jobs").update({name:document.getElementById("en").value.trim(),description:document.getElementById("ed").value.trim()||null,visibility:document.getElementById("ev").value}).eq("id",S.job.id).select().single();if(r.error)return toast(r.error.message,true);S.job=r.data;S.jobs=S.jobs.map(j=>j.id===r.data.id?r.data:j);render();toast("Saved.")}
const originalRender=render;
render=async function(){theme();if(!S.user||!S.profile){app.innerHTML=auth();return}app.innerHTML=wrap(S.profile.role==="manager"?manager():worker());if(S.job){if(S.profile.role==="manager"&&S.tab==="home")await loadManagerHome();if(S.profile.role==="manager"&&S.tab==="workers")await loadWorkers();if(S.profile.role==="manager"&&S.tab==="requests")await loadRequests();if(S.profile.role==="manager"&&S.tab==="tasks")await loadTasks();if(S.profile.role==="worker"&&S.tab==="home")await loadWorkerHome()}}
}
